import { readFile } from 'node:fs/promises';

const configSource = await readFile(new URL('../src/data/site-config.ts', import.meta.url), 'utf8');
const adsTxt = await readFile(new URL('../public/ads.txt', import.meta.url), 'utf8');

const readString = (name) => {
  const match = configSource.match(new RegExp(`export const ${name} = '([^']*)'`));
  return match?.[1] ?? '';
};

const enabled = /export const ADSENSE_ENABLED = true/.test(configSource);
const publisherId = readString('ADSENSE_PUBLISHER_ID');
const pubId = readString('ADSENSE_PUB_ID');
const slot = readString('ADSENSE_AD_SLOT');
const cmpUrl = readString('ADSENSE_CMP_SCRIPT_URL');

if (!enabled) {
  console.log('AdSense disabled. No ad loader, ad units, or CMP script should be emitted.');
  process.exit(0);
}

const errors = [];
if (!/^ca-pub-\d{16}$/.test(publisherId)) errors.push('ADSENSE_PUBLISHER_ID must be ca-pub- followed by 16 digits.');
if (!/^pub-\d{16}$/.test(pubId)) errors.push('ADSENSE_PUB_ID must be pub- followed by 16 digits.');
if (!/^\d+$/.test(slot)) errors.push('ADSENSE_AD_SLOT must be numeric.');
if (!cmpUrl.startsWith('https://')) errors.push('ADSENSE_CMP_SCRIPT_URL must be the HTTPS URL generated by Google Privacy & messaging.');
if (!new RegExp(`^google\\.com, ${pubId.replace('-', '\\-')}, (DIRECT|RESELLER), `, 'm').test(adsTxt)) {
  errors.push('public/ads.txt must contain the exact Google authorized-seller line for ADSENSE_PUB_ID.');
}

if (errors.length > 0) {
  console.error(errors.map((error) => `- ${error}`).join('\n'));
  process.exit(1);
}

console.log('AdSense configuration passes format and ads.txt checks.');
